true
Signed-off-by: Rina Fujino <rina.fujino.23@gmail.com>

diff --git a/.github/workflows/test-warning.yml b/.github/workflows/test-warning.yml
--- a/.github/workflows/test-warning.yml
+++ b/.github/workflows/test-warning.yml
@@ -23,4 +23,4 @@ jobs:
       # この特殊な形式の出力は、GitHub Actionsによって解釈され、
       # ワークフロー実行結果の「Annotations」セクションに警告として表示されます。
       - name: Show Warning Message
-        run: false || { echo "::warning title=Retried build for ${{ matrix.item }}::The initial build for ${{ matrix.item }} failed and retried." && echo "next"; }
+        run: true || { echo "::warning title=Retried build for ${{ matrix.item }}::The initial build for ${{ matrix.item }} failed and retried." && echo "next"; }
